updated prepush to check branches

diff --git a/bin/git-hooks/pre-push b/bin/git-hooks/pre-push
--- a/bin/git-hooks/pre-push
+++ b/bin/git-hooks/pre-push
@@ -4,40 +4,59 @@ sleep 1
 
 target_docker_name="front"
 
-bash $PWD/bin/setup-docker.sh $target_docker_name
-if [ $? != 0 ]
-then
-    >&2 echo "[post-merge] no $target_docker_name docker-machine running"
-    exit 1
-fi
-
-echo "[post-merge] connecting to containers"
-eval $(docker-machine env $target_docker_name)
-
-echo "[pre-push] Running lint"
-docker-compose run -T --rm node gulp lint --color >> push.log 2>&1
-
+git update-index -q --refresh
+git diff-index --quiet HEAD .
 if [ $? != 0 ]; then
-    echo "build failed linting"
-    cat testlint.log 2>/dev/null
-    cat configlint.log 2>/dev/null
-    ./pretty_print_scss_log.js
-    cat jslint.log 2>/dev/null
+    echo "[91m[pre-push] branch is dirty. Please stash or commit your changes so the pre-push check can run[0m"
     exit 157
 fi
 
-echo "[pre-push] Running Unit Tests"
-docker-compose run --rm node gulp unit --color >> push_test.log 2>&1
+z40=0000000000000000000000000000000000000000
 
-if [ $? != 0 ]; then
-    echo "build failed unit tests"
-    cat push_test.log
-    exit 157
-fi
+while read local_ref local_sha remote_ref remote_sha
+do
+    current_sha1=$(git rev-parse HEAD)
+    current_branch=$(git rev-parse --abbrev-ref HEAD)
+    if [ "$local_sha" != $z40 ] && [ "$local_sha" != "$current_sha1" ]; then
+        git checkout $local_sha
 
-echo "" > testlint.log
-echo "" > configlint.log
-echo "" > jslint.log
-echo "" > scsslint.json
-echo "" > push_test.log
+            bash $PWD/bin/setup-docker.sh $target_docker_name
+            if [ $? != 0 ]
+            then
+                >&2 echo "[post-merge] no $target_docker_name docker-machine running"
+                exit 1
+            fi
 
+            echo "[post-merge] connecting to containers"
+            eval $(docker-machine env $target_docker_name)
+
+            echo "[pre-push] Running lint"
+            docker-compose run -T --rm node gulp lint --color >> push.log 2>&1
+
+            if [ $? != 0 ]; then
+                echo "build failed linting"
+                cat testlint.log 2>/dev/null
+                cat configlint.log 2>/dev/null
+                ./pretty_print_scss_log.js
+                cat jslint.log 2>/dev/null
+                exit 157
+            fi
+
+            echo "[pre-push] Running Unit Tests"
+            docker-compose run --rm node gulp unit --color >> push_test.log 2>&1
+
+            if [ $? != 0 ]; then
+                echo "build failed unit tests"
+                cat push_test.log
+                exit 157
+            fi
+
+            echo "" > testlint.log
+            echo "" > configlint.log
+            echo "" > jslint.log
+            echo "" > scsslint.json
+            echo "" > push_test.log
+
+        git checkout $current_branch
+    fi
+done
